import { aiCategories, type AiCategory } from "@/lib/config/ai-categories";

export type CategoryKeywordPack = {
  category: AiCategory;
  intent: string;
  keywords: readonly string[];
};

export const categoryKeywordPacks = {
  Agents: {
    category: "Agents",
    intent:
      "Find agentic systems, autonomous workflows, tool-using models, orchestration frameworks and computer-use agents.",
    keywords: [
      "AI agents",
      "autonomous agents",
      "agentic AI",
      "agentic workflow",
      "AI agent framework",
      "multi-agent systems",
      "multi agent orchestration",
      "agent orchestration",
      "tool calling agents",
      "function calling agents",
      "computer use agents",
      "browser agents",
      "coding agents",
      "workflow agents",
      "AI coworker",
      "AI assistant framework",
      "agent memory",
      "agent planning",
      "agent evaluation",
      "agent benchmark",
      "LangGraph agents",
      "CrewAI agents",
      "AutoGen agents",
      "OpenAI agents SDK",
      "MCP agents",
      "model context protocol agents",
      "agent tools",
      "agent runtime",
      "agent observability",
      "agentic automation",
      "AI task automation agent",
      "AI research agent",
      "personal AI agent",
      "enterprise AI agents",
      "agent reliability",
      "agent guardrails",
    ],
  },
  Coding: {
    category: "Coding",
    intent:
      "Find AI software development tools, coding agents, IDE workflows, code review tools and developer productivity signals.",
    keywords: [
      "AI coding",
      "AI coding assistant",
      "coding agent",
      "AI software engineer",
      "AI developer tools",
      "AI code review",
      "AI pair programmer",
      "agentic coding",
      "code generation model",
      "AI bug fixing",
      "AI refactoring",
      "AI code search",
      "AI terminal assistant",
      "AI IDE",
      "VS Code AI",
      "Cursor AI",
      "Windsurf AI",
      "Claude Code",
      "GitHub Copilot",
      "open source coding agent",
      "software engineering benchmark",
      "SWE-bench",
      "code execution agent",
      "AI test generation",
      "AI pull request",
      "repository agent",
      "AI DevOps",
      "developer workflow AI",
      "codebase understanding",
      "LLM for programming",
      "AI documentation generator",
      "AI migration tool",
      "AI debugging tool",
      "AI code completion",
      "AI code interpreter",
    ],
  },
  Video: {
    category: "Video",
    intent:
      "Find AI video generation, editing, avatars, animation, creator workflows and production tooling.",
    keywords: [
      "AI video",
      "AI video generation",
      "text to video model",
      "image to video AI",
      "video diffusion model",
      "AI video editing",
      "AI video workflow",
      "AI animation",
      "AI film tool",
      "AI creator video",
      "generative video",
      "video generation model",
      "video foundation model",
      "AI b-roll generator",
      "AI short-form video",
      "AI video ads",
      "AI video avatar",
      "AI talking head",
      "AI lip sync",
      "AI motion transfer",
      "AI storyboard",
      "AI scene generation",
      "runway video AI",
      "Pika AI video",
      "Sora video AI",
      "Kling AI video",
      "Luma Dream Machine",
      "Veo AI video",
      "AI video upscaling",
      "AI video localization",
      "AI video dubbing",
      "AI video repurposing",
      "AI video editing agent",
      "AI YouTube workflow",
      "synthetic video",
    ],
  },
  Image: {
    category: "Image",
    intent:
      "Find AI image generation, editing, diffusion workflows, design tooling and visual content pipelines.",
    keywords: [
      "AI image generation",
      "text to image model",
      "image generation workflow",
      "AI image editing",
      "AI design tool",
      "diffusion model",
      "latent diffusion",
      "image diffusion model",
      "AI photo editing",
      "generative image AI",
      "ComfyUI workflow",
      "Stable Diffusion workflow",
      "ControlNet",
      "LoRA training",
      "Flux AI image",
      "Midjourney workflow",
      "DALL-E image generation",
      "image prompt engineering",
      "AI product photography",
      "AI ad creative",
      "AI brand design",
      "AI illustration",
      "AI image upscaling",
      "AI background removal",
      "AI image inpainting",
      "AI image outpainting",
      "AI visual editor",
      "AI design system",
      "AI mockup generator",
      "AI fashion image",
      "AI architecture rendering",
      "AI creative workflow",
      "synthetic image dataset",
      "visual generative AI",
      "AI image model benchmark",
    ],
  },
  Audio: {
    category: "Audio",
    intent:
      "Find AI audio, voice, music, speech, dubbing, podcast and sound production tooling.",
    keywords: [
      "AI audio",
      "AI voice generation",
      "text to speech AI",
      "speech to text AI",
      "AI music generation",
      "AI sound generation",
      "voice cloning",
      "AI dubbing",
      "AI audio editing",
      "AI podcast tool",
      "AI voice agent",
      "speech model",
      "audio language model",
      "AI transcription",
      "AI meeting notes audio",
      "real time speech translation",
      "AI voiceover",
      "AI sound design",
      "AI mastering",
      "AI music production",
      "AI audio enhancement",
      "AI noise removal",
      "voice synthesis",
      "speech synthesis model",
      "AI call center voice",
      "AI pronunciation coach",
      "AI audio separation",
      "AI stem splitter",
      "AI audiobook narration",
      "multimodal audio model",
      "AI accent conversion",
      "AI voice safety",
    ],
  },
  "Open Source": {
    category: "Open Source",
    intent:
      "Find open-source AI models, tools, frameworks, infrastructure and fast-growing repositories.",
    keywords: [
      "open source AI",
      "open source LLM",
      "open source AI model",
      "open source agent framework",
      "open source RAG",
      "open weights model",
      "AI GitHub repository",
      "AI framework GitHub",
      "LLM framework",
      "AI developer framework",
      "open source inference",
      "open source fine tuning",
      "open source multimodal model",
      "open source coding agent",
      "open source AI tool",
      "open source AI workflow",
      "open source vector database",
      "open source evaluation framework",
      "open source AI observability",
      "open source model serving",
      "open source model routing",
      "open source embeddings",
      "open source computer vision AI",
      "open source speech model",
      "open source diffusion model",
      "Hugging Face open source model",
      "Apache licensed AI model",
      "MIT licensed AI tool",
      "local open source AI",
      "self hosted AI",
      "AI infrastructure open source",
      "open model benchmark",
    ],
  },
  "Local LLM": {
    category: "Local LLM",
    intent:
      "Find local models, private inference, on-device AI, self-hosted LLM stacks and edge deployment signals.",
    keywords: [
      "local LLM",
      "local AI model",
      "on-device AI",
      "private LLM",
      "self hosted LLM",
      "offline AI assistant",
      "edge AI model",
      "small language model",
      "SLM",
      "quantized LLM",
      "GGUF model",
      "Ollama model",
      "llama.cpp",
      "LM Studio",
      "local RAG",
      "private RAG",
      "local inference",
      "CPU inference LLM",
      "GPU inference LLM",
      "Apple Silicon LLM",
      "NPU AI model",
      "on-device speech model",
      "local multimodal model",
      "local coding model",
      "enterprise private AI",
      "air gapped LLM",
      "local AI workflow",
      "model quantization",
      "low latency inference",
      "AI model serving local",
      "personal AI server",
      "privacy preserving LLM",
    ],
  },
  Automation: {
    category: "Automation",
    intent:
      "Find workflow automation, AI operations, business process automation and AI-powered integrations.",
    keywords: [
      "AI automation",
      "workflow automation AI",
      "AI workflow",
      "AI process automation",
      "AI operations",
      "agentic automation",
      "AI business automation",
      "AI task automation",
      "AI browser automation",
      "AI desktop automation",
      "AI data entry automation",
      "AI lead generation automation",
      "AI customer support automation",
      "AI email automation",
      "AI spreadsheet automation",
      "AI CRM automation",
      "AI sales automation",
      "AI ops agent",
      "AI workflow builder",
      "no-code AI automation",
      "Zapier AI automation",
      "n8n AI workflow",
      "Make.com AI automation",
      "AI integration platform",
      "AI document automation",
      "AI invoice processing",
      "AI research automation",
      "AI reporting automation",
      "AI back office automation",
      "AI internal tools",
      "AI process mining",
      "AI autonomous workflow",
    ],
  },
  Research: {
    category: "Research",
    intent:
      "Find AI research papers, benchmarks, evals, model releases, alignment, architectures and scientific signals.",
    keywords: [
      "AI research",
      "LLM research",
      "machine learning paper",
      "arXiv AI paper",
      "AI benchmark",
      "LLM evaluation",
      "AI evals",
      "model evaluation",
      "AI alignment",
      "AI safety research",
      "model interpretability",
      "mechanistic interpretability",
      "multimodal model research",
      "foundation model research",
      "reasoning model",
      "test time compute",
      "synthetic data research",
      "AI scaling law",
      "mixture of experts model",
      "MoE model",
      "retrieval augmented generation research",
      "RAG evaluation",
      "agent benchmark",
      "long context model",
      "AI hallucination evaluation",
      "AI robustness",
      "AI watermarking",
      "AI governance research",
      "AI model compression",
      "AI distillation",
      "continual learning AI",
      "world model AI",
      "reinforcement learning AI",
      "AI reasoning benchmark",
    ],
  },
  Marketing: {
    category: "Marketing",
    intent:
      "Find AI marketing tools, creative generation, growth workflows, SEO, ads and content production signals.",
    keywords: [
      "AI marketing",
      "AI content marketing",
      "AI SEO tool",
      "AI ad creative",
      "AI growth marketing",
      "AI social media tool",
      "AI copywriting",
      "AI brand strategy",
      "AI market research",
      "AI audience research",
      "AI campaign automation",
      "AI email marketing",
      "AI landing page generator",
      "AI sales copy",
      "AI creative testing",
      "AI performance marketing",
      "AI influencer marketing",
      "AI UGC ads",
      "AI video ads",
      "AI product marketing",
      "AI customer insights",
      "AI competitor analysis",
      "AI newsletter tool",
      "AI content repurposing",
      "AI LinkedIn content",
      "AI TikTok content",
      "AI brand design tool",
      "AI media buying",
      "AI personalization marketing",
      "AI marketing analytics",
      "AI ecommerce marketing",
      "AI local SEO",
    ],
  },
  Business: {
    category: "Business",
    intent:
      "Find business AI adoption, enterprise tooling, productivity, revenue workflows and startup/product signals.",
    keywords: [
      "AI business",
      "enterprise AI",
      "AI startup",
      "AI SaaS",
      "AI productivity tool",
      "AI copilot for business",
      "AI analytics platform",
      "AI business intelligence",
      "AI knowledge management",
      "AI customer support",
      "AI sales assistant",
      "AI finance tool",
      "AI legal tech",
      "AI HR tool",
      "AI procurement",
      "AI operations platform",
      "AI workflow platform",
      "AI enterprise search",
      "AI document intelligence",
      "AI meeting assistant",
      "AI CRM",
      "AI startup funding",
      "AI product launch",
      "AI monetization",
      "AI compliance platform",
      "AI decision intelligence",
      "AI strategy tool",
      "AI internal knowledge base",
      "AI consulting automation",
      "AI agent for business",
      "vertical AI SaaS",
      "AI revenue operations",
    ],
  },
  Education: {
    category: "Education",
    intent:
      "Find AI tutoring, learning platforms, assessment, education operations and academic productivity signals.",
    keywords: [
      "AI education",
      "AI tutor",
      "AI learning platform",
      "AI teaching assistant",
      "AI classroom tool",
      "AI lesson planner",
      "AI assessment tool",
      "AI grading",
      "AI study assistant",
      "AI personalized learning",
      "AI course creator",
      "AI student support",
      "AI academic writing tool",
      "AI research assistant education",
      "AI language learning",
      "AI math tutor",
      "AI coding tutor",
      "AI exam prep",
      "AI learning analytics",
      "AI curriculum design",
      "AI university operations",
      "AI school administration",
      "AI feedback tool",
      "AI note taking for students",
      "AI education policy",
      "AI plagiarism detection",
      "AI LMS integration",
      "AI accessibility education",
      "AI teacher productivity",
      "AI student retention",
      "AI virtual classroom",
    ],
  },
  Security: {
    category: "Security",
    intent:
      "Find AI security, cyber defense, model safety, prompt injection, privacy, compliance and adversarial ML signals.",
    keywords: [
      "AI security",
      "LLM security",
      "prompt injection",
      "AI cyber security",
      "AI red teaming",
      "AI safety tool",
      "AI guardrails",
      "AI privacy",
      "model security",
      "AI vulnerability",
      "AI phishing detection",
      "AI SOC analyst",
      "AI threat detection",
      "AI malware analysis",
      "AI code security",
      "AI supply chain security",
      "AI data leakage",
      "LLM data exfiltration",
      "jailbreak detection",
      "AI compliance",
      "AI governance platform",
      "AI risk management",
      "AI audit tool",
      "AI policy enforcement",
      "AI access control",
      "model watermarking",
      "adversarial machine learning",
      "AI penetration testing",
      "AI security benchmark",
      "AI incident response",
      "secure RAG",
      "LLM observability security",
    ],
  },
  Robotics: {
    category: "Robotics",
    intent:
      "Find embodied AI, robot learning, humanoids, VLA models, manipulation, autonomy and physical-world AI signals.",
    keywords: [
      "AI robotics",
      "robotics foundation model",
      "embodied AI",
      "physical AI",
      "robot learning",
      "humanoid robot",
      "humanoid robotics AI",
      "robot manipulation",
      "robot policy learning",
      "vision language action model",
      "VLA model",
      "robotics VLA",
      "robotics transformer",
      "robot foundation model",
      "robotics world model",
      "sim2real robotics",
      "robot imitation learning",
      "robot reinforcement learning",
      "robot grasping AI",
      "robot navigation AI",
      "AI autonomous robot",
      "warehouse robot AI",
      "home robot AI",
      "robotics dataset",
      "robotics benchmark",
      "robot motion planning AI",
      "robot task planning",
      "robot perception model",
      "robotics teleoperation",
      "robotics diffusion policy",
      "generalist robot policy",
      "robotics control model",
      "embodied agent",
      "real-world robot learning",
      "AI for drones robotics",
    ],
  },
  "General AI": {
    category: "General AI",
    intent:
      "Find broad AI platform, model release, multimodal, infrastructure, adoption and ecosystem signals.",
    keywords: [
      "artificial intelligence",
      "generative AI",
      "large language model",
      "LLM",
      "foundation model",
      "multimodal AI",
      "AI model release",
      "AI platform",
      "AI assistant",
      "AI copilot",
      "AI workflow",
      "RAG",
      "retrieval augmented generation",
      "embeddings model",
      "vector database AI",
      "model routing",
      "AI inference",
      "AI model serving",
      "AI evaluation",
      "AI benchmark",
      "AI observability",
      "AI infrastructure",
      "AI API",
      "AI app builder",
      "AI search",
      "AI reasoning",
      "AI memory",
      "AI knowledge base",
      "enterprise AI adoption",
      "AI regulation",
      "AI governance",
      "AI ecosystem",
      "AI trend",
      "AI tools",
      "AI product launch",
      "AI research breakthrough",
    ],
  },
} as const satisfies Record<AiCategory, CategoryKeywordPack>;

export function getCategoryKeywordPack(category: AiCategory): CategoryKeywordPack {
  return categoryKeywordPacks[category];
}

export function getCategoryKeywordCount(category: AiCategory): number {
  return categoryKeywordPacks[category].keywords.length;
}

export function getKeywordCoverageSummary() {
  return aiCategories.map((category) => {
    const pack = getCategoryKeywordPack(category);
    return {
      category,
      intent: pack.intent,
      keywordCount: pack.keywords.length,
      status:
        pack.keywords.length >= 28
          ? "Ready"
          : pack.keywords.length >= 18
            ? "Review"
            : "Thin coverage",
    };
  });
}
